version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: user_interactions_db
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: your_secure_password_here
    ports: 
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes: 
      - dbdata:/var/lib/mysql
volumes: 
  dbdata: {}